### ISSUE TITLE
挺不错的，那么你是怎么解决很长的那种图片的质量的问题呢？

### ISSUE THREAD

**Issue by kaleai** [KayWu/Duitang#1]

**Comment by KayWu** [comment]
这是当初学习时写的Demo，连图片都是本地写死的。
我谈一下对这个问题的想法。
如果是瀑布流的图片很长的话，我觉得应该对其做一些比例上的限制。可以在用户上传时限制比例或者服务器根据原图生成缩略图时规定一个合理的比例范围。不然由于图片过长，整个瀑布流的效果也不会太好。
如果是单张图片显示的话，若长宽不超过 2000，图片加载库一般都能处理。若是超长的图，可能会考虑图片分块加载渲染。
BTW，用过 CommonAdapter，挺好用的。

**Comment by kaleai** [comment]
我想说下我自己的想法哈：
大图：服务器和上传的地方都应该对于很大的图片做处理，否则一个图片100M，这个丢给客户端是不现实的。其次就是客户端处理，服务器没办法对图片做差异性处理。客户端的处理方式可以采用上传手机屏幕大小，然后去服务器拿特定大小的图片，从一定的情况下保证内存的够用。但这也不是根本的方案，所以目前2完美的方案还没想好。

长图：这个的定义是图片大小可以展示，不会引起oom，但是图片很长。这个的话咱们可以考虑用开源库，开源库也就是用了那个局部decode的api，具体选择哪个开源库我也在考虑当中。

你的想法是怎样的呢？想讨论一下

**Comment by KayWu** [comment]
大图和长图都可以通过局部 decode 的 api 来解析，防止 OOM。
我用微信试了下，3722 \* 2292，299KB 图片是 OK 的。不过会变得比较卡。
这是个成本问题，通用的图片加载库 2000 以内的都是 OK 的。一般应用可以满足了。
若是相册之类的应用，对这些要求会比较高一些。

**Comment by kaleai** [comment]
感谢你的回复！
